### ISSUE TITLE
这个统计不含远程吗

### ISSUE THREAD

**Issue by luocheng610** [Witnesscm/MerInspect#2]
很奇怪，远程下了，分数不变
下了个副手，分数变了
然后不装副手的情况下，把远程装上去，分数统计好像变成正常了，但是我副手还没装上呢

装上副手后，分数变成不包含远程的呢。。。。。。

**Comment by Witnesscm** [comment]
主手和副手同时装备武器的情况下，按照主手+副手的装等计算
其他情况是以主手、副手、远程武器中装等最高的x2计算
原版插件就是这个逻辑，没有改动过

**Comment by luocheng610** [comment]
> 主手和副手同时装备武器的情况下，按照主手+副手的装等计算 其他情况为主手、副手、远程武器中装等最高的x2计算 原版插件就是这个逻辑，没有事件过

谢谢，知道逻辑啦。
